CREATE TABLE IF NOT EXISTS pelicula_proyeccion (
    movie_id VARCHAR(64) PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    precio_actual DECIMAL(12,2) NOT NULL,
    activa BOOLEAN NOT NULL,
    version BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS carrito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS carrito_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrito_id BIGINT NOT NULL,
    pelicula_id VARCHAR(64) NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    precio_unitario DECIMAL(12,2) NOT NULL,
    cantidad INT NOT NULL,
    CONSTRAINT fk_carrito_item_carrito FOREIGN KEY (carrito_id) REFERENCES carrito(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id VARCHAR(128) NOT NULL,
    fecha_hora TIMESTAMP NOT NULL,
    subtotal DECIMAL(12,2) NOT NULL,
    descuento_aplicado DECIMAL(12,2) NOT NULL,
    total DECIMAL(12,2) NOT NULL,
    estado VARCHAR(32) NOT NULL DEFAULT 'CONFIRMADA',
    motivo_rechazo VARCHAR(64),
    detalles_rechazo VARCHAR(1000)
);

CREATE INDEX IF NOT EXISTS idx_compra_cliente_fecha ON compra(cliente_id, fecha_hora DESC);

CREATE TABLE IF NOT EXISTS compra_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id BIGINT NOT NULL,
    pelicula_id VARCHAR(64) NOT NULL,
    titulo_al_comprar VARCHAR(255) NOT NULL,
    precio_al_comprar DECIMAL(12,2) NOT NULL,
    cantidad INT NOT NULL,
    subtotal DECIMAL(12,2) NOT NULL,
    CONSTRAINT fk_compra_item_compra FOREIGN KEY (compra_id) REFERENCES compra(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    payload_json VARCHAR(8000) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    published_at TIMESTAMP,
    attempts INT NOT NULL,
    last_error VARCHAR(1000)
);

CREATE INDEX IF NOT EXISTS idx_outbox_status_created ON outbox_event(status, created_at);

CREATE TABLE IF NOT EXISTS processed_events (
    event_id VARCHAR(64) PRIMARY KEY,
    processed_at TIMESTAMP NOT NULL
);
